### ISSUE TITLE
ZeroDivisionError in computeDFF

### ISSUE THREAD

**Issue by deep-introspection** [agiovann/CalBlitz#3]
Hi!

thanks to have created this very nice project. I am getting into it and would be much happy to contribute.
For now, I made some corrections in the README and try to make the test_software.py to work.
After minor adjustment, I end up with the script running well until the call of `computeDFF`.
Here a ZeroDivisionError since the `downsampfact` variable in `computeDFF` is set that way:
```
 downsampfact=int(secsWindow*1./self.fr);
```
which set to zero since self.fr~15

I tried to remove the integer cast but then other error appear...
What would be the proper way to repair this?

Cheers,
Guillaume

**Comment by agiovann** [comment]
Thank you Guillaume,

Nice meeting you. That is great news! Let me know if you want to chat about
the plan.

Cheers

**Comment by agiovann** [comment]
About the error, it is possible that there is sure inconsistencies in old
functions. At the beginning I was using the inter frame interval instead of
the rate. So I think it is enough to multiply instead of dividing by self.fr
.

Cheers

**Comment by deep-introspection** [comment]
Thanks Andrea, multiplication apparently solved the issue. It says: 'Everything should be alright!' ;)
Glad to be on board. I am also working on autism and my lab is collaborating with the Simons. What a small world!
Anyway, we can arrange a Skype meeting if you want. My handle is deep-introspection
Cheers!
