### ISSUE TITLE
test_software.py error

### ISSUE THREAD

**Issue by bafonso** [agiovann/CalBlitz#6]
Just installed and tried running the test.

>(calblitz) afonsob-lm1:CalBlitz afonsob$ python test_software.py
loading movie...
motion correcting...
/Users/afonsob/CalBlitz/calblitz/movies.py:194: UserWarning: Casting the array to float 32
  warnings.warn('Casting the array to float 32')
Frame 100
Frame 200
Frame 300
Frame 400
/Users/afonsob/CalBlitz/calblitz/movies.py:284: UserWarning: Casting the array to float 32
  warnings.warn('Casting the array to float 32')
cubic interpolation
Frame 100
Frame 200
Frame 300
Frame 400
Frame 100
Frame 200
Frame 300
Frame 400
Frame 500
Frame 600
Frame 700
Frame 800
Frame 900
Frame 1000
Frame 1100
Frame 1200
Frame 1300
Frame 1400
cubic interpolation
Frame 100
Frame 200
Frame 300
Frame 400
Frame 500
Frame 600
Frame 700
Frame 800
Frame 900
Frame 1000
Frame 1100
Frame 1200
Frame 1300
Frame 1400
Frame 100
Frame 200
Frame 300
Frame 400
Frame 500
Frame 600
Frame 700
Frame 800
Frame 900
Frame 1000
Frame 1100
Frame 1200
Frame 1300
Frame 1400
cubic interpolation
Frame 100
Frame 200
Frame 300
Frame 400
Frame 500
Frame 600
Frame 700
Frame 800
Frame 900
Frame 1000
Frame 1100
Frame 1200
Frame 1300
Frame 1400
Traceback (most recent call last):
  File "test_software.py", line 38, in <module>
    m=m.crop(crop_top=max_h,crop_bottom=-min_h+1,crop_left=max_w,crop_right=-min_w,crop_begin=0,crop_end=0)
  File "/Users/afonsob/CalBlitz/calblitz/movies.py", line 396, in crop
    return self[crop_begin:t-crop_end,crop_top:h-crop_bottom,crop_left:w-crop_right]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by agiovann** [comment]
Hello Alonso. This is a legacy package. Please refer to this new one https://github.com/simonsfoundation/CaImAn. 
Best
Andrea

**Comment by bafonso** [comment]
Thanks!
